# **_Linear Algebra: Is Trace a Linear Operator?_**

<hr style="height: 0; box-shadow: 0 0 5px 4px gold; width: 95%;">

## **_Description:_**

This Python Jupyter notebook consists of my solution to an exercise from Mike X. Cohen's Linear Algebra course on Udemy.

-   Udemy course: https://www.udemy.com/course/linear-algebra-theory-and-implementation

-   Professor Cohen's website: https://www.mikexcohen.com/

<hr style="height: 0; box-shadow: 0 0 5px 4px dodgerblue; width: 95%;">

## **_Instructions:_**

-   Determine the relationship between these two expressions:

$$
\Large
    tr(\textbf{A}) + tr(\textbf{B})
    \; \; \text{and} \; \;
    tr(\textbf{A} + \textbf{B})
$$

-   Determine the relationship between these two expressions:

$$
\Large
    tr(\lambda \times \textbf{A})
    \; \; \text{and} \; \;
    \lambda \times tr(\textbf{A})
$$

-   $\textbf{A}$ and $\textbf{B}$ are each random-value $(m \times n)$ square matrices.

-   $\lambda$ is a random-value scalar.

-   Display each operation in the output.

#### **_If TRACE is a linear operator then each individual pair should be equal._**

#### **_Notes:_**

-   I'm adding constants from `scipy` for fun.

-   Also made a small function to handle spacing when printing to output.

<hr style="height: 0; box-shadow: 0 0 5px 4px forestgreen; width: 95%;">

## **_Solution:_**

In [1]:
# Import libraries:
import numpy as np
from scipy.constants import blob, kilo, speed_of_light, speed_of_sound


def print_awesome(info_str, data):
    """Prints string and data in a well-spaced fashion."""
    print(info_str, data, sep="\n", end="\n\n")


# Define shape:
m = 5
n = 5

# Define matrices and scalar:
M_SOUND = np.random.rand(m, n) * kilo / speed_of_sound
M_LIGHT = np.random.randn(m, n) * speed_of_light / kilo**3
l_blob = np.random.randint(1, 10) * blob / kilo

# Print matrices and scalar:
print_awesome("Speed of Sound Matrix:", M_SOUND)
print_awesome("Speed of Light Matrix:", M_LIGHT)
print_awesome("Scalar Lambda:", l_blob)

# Define conclusion bools as False to begin:
lin_add_valid = False
lin_mult_valid = False
overall_conclusion = False

# Get sums two ways, round so we don't get lost in the weeds:
tr_add_sep = np.round(np.trace(M_SOUND) + np.trace(M_LIGHT), 2)
tr_add_comb = np.round(np.trace(np.add(M_SOUND, M_LIGHT)), 2)
# Conclude whether addition property is valid:
lin_add_valid = tr_add_sep == tr_add_comb

# Print additon conclusion:
print_awesome("Separate Addition:", tr_add_sep)
print_awesome("Combined Addition:", tr_add_comb)
print_awesome("TRACE closed under addition?", lin_add_valid)

# Get products two ways, round to clarify comparison:
tr_mult_sep = np.round(np.trace(l_blob * M_SOUND), 2)
tr_mult_comb = np.round(l_blob * np.trace(M_SOUND), 2)
# Conclude whether multiplication property is valid:
lin_mult_valid = tr_mult_sep == tr_mult_comb

# Print scalar-multiplication conclusion:
print_awesome("Separate Multiplication:", tr_mult_sep)
print_awesome("Combined Multiplication:", tr_mult_comb)
print_awesome("TRACE closed under scalar-multiplication?", lin_mult_valid)

# Overall conclusion:
overall_conclusion = lin_add_valid and lin_mult_valid
print_awesome("TRACE is a Linear Operator?", overall_conclusion)

Speed of Sound Matrix:
[[2.16119294 1.72161268 1.21242273 1.65406785 2.28919244]
 [1.98754842 0.1448649  2.80120112 0.48724299 0.02917485]
 [2.55056964 1.18863382 1.70784523 0.73670756 2.63086064]
 [1.57883823 0.49036873 0.70808781 1.13255422 0.02141113]
 [0.79212251 0.10683232 2.30659354 0.28582434 0.82350166]]

Speed of Light Matrix:
[[-0.0033221  -0.35135063  0.5513535   0.0225583   0.13701305]
 [-0.53944065  0.70945159 -0.03929814 -0.3254106   0.49609926]
 [-0.04310278 -0.5478986   0.24494298  0.21636546 -0.47335   ]
 [ 0.01930931  0.12353816  0.17332891  0.35957815 -0.1308674 ]
 [-0.15875384 -0.08101521  0.0965529  -0.24987218  0.20507973]]

Scalar Lambda:
0.17512683524647635

Separate Addition:
7.49

Combined Addition:
7.49

TRACE closed under addition?
True

Separate Multiplication:
1.05

Combined Multiplication:
1.05

TRACE closed under scalar-multiplication?
True

TRACE is a Linear Operator?
True



<hr style="height: 0; box-shadow: 0 0 5px 4px crimson; width: 95%;">

## **_Conclusion:_**

#### **_1. Trace IS a linear operator because:_**

$$
\Large
    tr(\textbf{A}) + tr(\textbf{B})
    \; \; = \; \;
    tr(\textbf{A} + \textbf{B})
$$

$$
\Large
    tr(\lambda \times \textbf{A})
    \; \; = \; \;
    \lambda \times tr(\textbf{A})
$$

-   Performing addition/scalar-multiplication on matrix elements before and after applying the trace function returns the same result.

<hr style="height: 0; box-shadow: 0 0 5px 4px darkslateblue; width: 95%;">

<font size=2>

_Andrew Blais, Boston, Massachusetts_

GitHub: https://github.com/andrewblais

Website/Python Web Development Porfolio: https://www.andrewblais.dev/

</font>