# **_Linear Algebra: Is Trace a Linear Operator?_**

<hr style="height: 0; box-shadow: 0 0 5px 4px gold; width: 95%;">

## **_Description:_**

This Python Jupyter notebook consists of my solution to an exercise from Mike X. Cohen's Linear Algebra course on Udemy.

-   Udemy course: https://www.udemy.com/course/linear-algebra-theory-and-implementation

-   Professor Cohen's website: https://www.mikexcohen.com/

<hr style="height: 0; box-shadow: 0 0 5px 4px dodgerblue; width: 95%;">

## **_Instructions:_**

-   Determine the relationship between these two expressions:

$$
\Large
    tr(\textbf{A}) + tr(\textbf{B})
    \; \; \text{and} \; \;
    tr(\textbf{A} + \textbf{B})
$$

-   Determine the relationship between these two expressions:

$$
\Large
    tr(\lambda \times \textbf{A})
    \; \; \text{and} \; \;
    \lambda \times tr(\textbf{A})
$$

-   $\textbf{A}$ and $\textbf{B}$ are each random-value $(m \times n)$ square matrices.

-   $\lambda$ is a random-value scalar.

-   Display each operation in the output.

#### **_If TRACE is a linear operator then each individual pair should be equal._**

#### **_Notes:_**

-   I'm adding constants from `scipy` for fun.

-   Also made a small function to handle spacing when printing to output.

<hr style="height: 0; box-shadow: 0 0 5px 4px forestgreen; width: 95%;">

## **_Solution:_**

In [1]:
# Import libraries:
import numpy as np
from scipy.constants import blob, kilo, speed_of_light, speed_of_sound


def print_awesome(info_str, data):
    """Prints string and data in a well-spaced fashion."""
    print(info_str, data, sep="\n", end="\n\n")


# Define shape:
m = 5
n = 5

# Define matrices and scalar:
M_SOUND = np.random.rand(m, n) * kilo / speed_of_sound
M_LIGHT = np.random.randn(m, n) * speed_of_light / kilo**3
l_blob = np.random.randint(1, 10) * blob / kilo

# Print matrices and scalar:
print_awesome("Speed of Sound Matrix:", M_SOUND)
print_awesome("Speed of Light Matrix:", M_LIGHT)
print_awesome("Scalar Lambda:", l_blob)

# Define conclusion bools as False to begin:
lin_add_valid = False
lin_mult_valid = False
overall_conclusion = False

# Get sums two ways, round so we don't get lost in the weeds:
tr_add_sep = np.round(np.trace(M_SOUND) + np.trace(M_LIGHT), 2)
tr_add_comb = np.round(np.trace(np.add(M_SOUND, M_LIGHT)), 2)
# Conclude whether addition property is valid:
lin_add_valid = tr_add_sep == tr_add_comb

# Print additon conclusion:
print_awesome("Separate Addition:", tr_add_sep)
print_awesome("Combined Addition:", tr_add_comb)
print_awesome("TRACE closed under addition?", lin_add_valid)

# Get products two ways, round to clarify comparison:
tr_mult_sep = np.round(np.trace(l_blob * M_SOUND), 2)
tr_mult_comb = np.round(l_blob * np.trace(M_SOUND), 2)
# Conclude whether multiplication property is valid:
lin_mult_valid = tr_mult_sep == tr_mult_comb

# Print scalar-multiplication conclusion:
print_awesome("Separate Multiplication:", tr_mult_sep)
print_awesome("Combined Multiplication:", tr_mult_comb)
print_awesome("TRACE closed under scalar-multiplication?", lin_mult_valid)

# Overall conclusion:
overall_conclusion = lin_add_valid and lin_mult_valid
print_awesome("TRACE is a Linear Operator?", overall_conclusion)

Speed of Sound Matrix:
[[1.327422   1.87489754 1.46049244 0.91835962 0.46799223]
 [2.67320258 0.4807803  1.76649223 1.7276328  2.85643025]
 [2.10198596 2.85360573 2.02018042 1.26502987 1.69456773]
 [1.52602108 2.53544883 1.66115978 0.99835466 0.3712007 ]
 [1.05219776 0.08158733 2.37213863 2.23930235 2.04288165]]

Speed of Light Matrix:
[[ 0.04926707  0.48378895 -0.17187758 -0.16280396 -0.18635792]
 [-0.29672264  0.08093934  0.3404663   0.0165921   0.23386081]
 [-0.13571944 -0.00061352  0.17491823 -0.27231775 -0.36380256]
 [ 0.15779122  0.25325545 -0.4330278   0.13868728  0.16196143]
 [-0.38893189  0.14327403 -0.44193675 -0.0252666  -0.04172299]]

Scalar Lambda:
1.4010146819718108

Separate Addition:
7.27

Combined Addition:
7.27

TRACE closed under addition?
True

Separate Multiplication:
9.62

Combined Multiplication:
9.62

TRACE closed under scalar-multiplication?
True

TRACE is a Linear Operator?
True



<hr style="height: 0; box-shadow: 0 0 5px 4px crimson; width: 95%;">

## **_Conclusion:_**

#### **_1. Trace IS a linear operator because:_**

$$
\Large
    tr(\textbf{A}) + tr(\textbf{B})
    \; \; = \; \;
    tr(\textbf{A} + \textbf{B})
$$

$$
\Large
    tr(\lambda \times \textbf{A})
    \; \; = \; \;
    \lambda \times tr(\textbf{A})
$$

-   Performing addition/scalar-multiplication on matrix elements before and after applying the trace function returns the same result.

<hr style="height: 0; box-shadow: 0 0 5px 4px darkslateblue; width: 95%;">

<font size=2>

_Andrew Blais, Boston, Massachusetts_

GitHub: https://github.com/andrewblais

Website/Python Web Development Porfolio: https://www.andrewblais.dev/

</font>