# **_Computing the Matrix Inverse Step by Step_**

### **_and comparing with NumPy's `np.linalg.inv()` method..._**

<hr style="height: 0; box-shadow: 0 0 5px 4px crimson; width: 95%;">

## **_Instructions:_**

### **_1. Implement the MCA Algorithm in code._**

##### **_M. Compute the MINORS Matrix._**

-   Replace each element with the determinant of the sub-matrix formed when exluding that element's row/col.

##### **_C. Create the COFACTORS Matrix:_**

-   Hadamard multiply the minors matrix by a matrix of the same size which is a grid of alternating `+`'s and `-`'s, _i.e._ `+1`'s and `-1`'s, _e.g._:

    $$
    \Large
        \begin{bmatrix}
            + & - & + \\
            - & + & - \\
            + & - & +
        \end{bmatrix}

        \quad \text{or} \quad

        \begin{bmatrix}
            +1 & -1 & +1 \\
            -1 & +1 & -1 \\
            +1 & -1 & +1
        \end{bmatrix}
    $$

-   The formula for this matrix is $h_{i, j} = (-1)^{i + j}$.

##### **_A. Compute the ADJUGATE Matrix:_**

-   Transpose the adjugate matrix and multiply by `1` over the **DETERMINANT** of the **ORIGINAL MATRIX**.

-   This will provide the inverse of the original matrix!

-   Remember to compute the determinant of the original matrix before any of the three 'MCA' steps -- if it's `0` there is no valid matrix inverse.

-   Only a **FULL-RANK** matrix, one that is not **SINGULAR**, can have an inverse.

-   Remember also that if the matrix is not **SQUARE**, there is no inverse.


<hr style="height: 0; box-shadow: 0 0 5px 4px dodgerblue; width: 85%;">

### **_2. Compute the inverse with [NumPy's](https://numpy.org/) `np.linalg.inv()` method._**

<hr style="height: 0; box-shadow: 0 0 5px 4px dodgerblue; width: 85%;">

### **_3. Compare the results._**

-   The difference between the matrix inverse computed manually via the MCA method and the matrix computed with NumPy's `np.linalg.inv()` method should be the `0`'s matrix.

<hr style="height: 0; box-shadow: 0 0 5px 4px crimson; width: 95%;">

This Python Jupyter notebook extrapolates from an exercise in Mike X. Cohen's Linear Algebra course on Udemy.

-   Udemy course: https://www.udemy.com/course/linear-algebra-theory-and-implementation

-   Professor Cohen's website: https://www.mikexcohen.com/

<hr style="height: 0; box-shadow: 0 0 5px 4px crimson; width: 95%;">

## **_Go:_**

In [ ]:
import numpy as np

In [13]:
# Indicate dimensionality:
N = 5

# Original Matrix:
A = np.random.randn(N, N)

# Instantiate Minors Matrix to populate:
A_MIN = np.zeros((N, N))

# Populate A_MIN with determinants of
#  submatrices comprising excluded rows
#  and cols:
for i in np.nditer(A):
    # Indicate which row/col match the 
    #  current element in the loop:
    row, col = np.where(A == i)
    # List to index rows of excluded rows:
    rows = [r for r in range(N) if r != row]
    # List to index rows of excluded columns:
    cols = [c for c in range(N) if c != col]
    # Indexing returns indicated sub-matrix:
    A_SUB = A[rows, :][:, cols]
    # Get the determinant:
    a_sub_det = np.linalg.det(A_SUB)
    # Add det to Minors Matrix at appropriate
    #  geography:
    A_MIN[row, col] = a_sub_det

# Initialize and populate matrix of 
#  alternating +1's and -1's:
A_H = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        # Remember to isolate -1 as per PEMDAS:
        A_H[i, j] = (-1) ** (i + j)

# Cofactors Matrix as Hadamard product of
#  Minors Matrix and +/-'s:
A_COF = A_MIN * A_H

# Adjugate matrix is transpose of Cofactors
#  Matrix:
A_ADJ = A_COF.T

# Determinant of Original Matrix:
a_det = np.linalg.det(A)

# Divide the Adjugate by A's det,
#  division written explicitly to
#  help me remember the formula:
A_INV = A_ADJ * (1 / a_det)

# Bypass above work by using NumPy's method:
A_INV_NP = np.linalg.inv(A)

# Print for Identity Matrix with 0's or
#  machine-zeros at off-diagonals:
ID = A @ A_INV
print("MCA METHOD, CHECK ACCURACY...")
print(f"A @ A_INV: Should be Identity Matrix (raw):\n{ID}\n")
# With 0's at the off-diags:
print(f"A @ A_INV: Should be Identity Matrix (rounded):\n{np.round(ID, 13)}\n")

# If our work was correct, this should produce
#  numbers VERY close to 0!
HOPEFULLY_MACHINE_ZEROS = A_INV - A_INV_NP
print("COMPARE ACCURACY OF MCA METHOD AGAINST NUMPY'S `np.linalg.inv()` METHOD...")
print(f"Difference between matrices, should be 0's (raw):\n{HOPEFULLY_MACHINE_ZEROS}\n")

# Actual zeros:
print(f"Difference between matrices, should be 0's (rounded):\n{np.round(HOPEFULLY_MACHINE_ZEROS, 13)}\n")

MCA METHOD, CHECK ACCURACY...
A @ A_INV: Should be Identity Matrix (raw):
[[ 1.00000000e+00  3.33430664e-17 -4.61924584e-16  1.82870298e-16
   1.17653171e-16]
 [-1.53305947e-16  1.00000000e+00  1.50534229e-16 -4.08304519e-17
  -4.32877635e-17]
 [-1.06268159e-16  4.08321787e-17  1.00000000e+00 -1.92382947e-16
  -8.94675474e-17]
 [-1.72484261e-17  2.49803209e-17  5.72427734e-16  1.00000000e+00
  -1.78226608e-16]
 [-1.76967176e-16 -5.73055070e-17 -1.98091748e-16 -9.92687340e-17
   1.00000000e+00]]

A @ A_INV: Should be Identity Matrix (rounded):
[[ 1.  0. -0.  0.  0.]
 [-0.  1.  0. -0. -0.]
 [-0.  0.  1. -0. -0.]
 [-0.  0.  0.  1. -0.]
 [-0. -0. -0. -0.  1.]]

COMPARE ACCURACY OF MCA METHOD AGAINST NUMPY'S `np.linalg.inv()` METHOD...
Difference between matrices, should be 0's (raw):
[[ 2.22044605e-16 -1.11022302e-16  4.44089210e-16  1.38777878e-16
  -5.55111512e-17]
 [ 0.00000000e+00 -5.55111512e-17 -1.11022302e-16  0.00000000e+00
   5.55111512e-17]
 [ 5.55111512e-17  5.55111512e-17  0.00

<hr style="height: 0; box-shadow: 0 0 5px 4px crimson; width: 95%;">

<hr style="height: 0; box-shadow: 0 0 5px 4px dodgerblue; width: 85%;">

<hr style="height: 0; box-shadow: 0 0 5px 4px #5EDC1F; width: 75%;">


<hr style="height: 0; box-shadow: 0 0 5px 4px magenta; width: 65%;">


<hr style="height: 0; box-shadow: 0 0 5px 4px gold; width: 55%;">

<font size=2>

_Andrew Blais, Boston, Massachusetts_

GitHub: https://github.com/andrewblais

Website/Python Web Development Porfolio: https://www.andrewblais.dev/

</font>